name: Transpiler

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Butane
        run: |
          wget https://github.com/coreos/butane/releases/latest/download/butane-x86_64-unknown-linux-gnu -O butane
          chmod +x butane

      - name: Transpile
        run: for file in *.bu; do ./butane --strict "{$file}" > "${file%.bu}".ign; done
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.ign
